import os
import requests
from bs4 import BeautifulSoup
import google.generativeai as genai

def scrape_and_analyze():
    print("=== Bharath-AI-Modules: Competitor Intel Scraper ===")
    
    # 1. Get User Input
    target_url = input("\nEnter the competitor URL to analyze: ").strip()
    
    # 2. Scrape the website text content
    print(f"\n[1/3] Scraping text content from: {target_url}...")
    try:
        headers = {'User-Agent': 'Mozilla/5.0'}
        response = requests.get(target_url, headers=headers, timeout=15)
        response.raise_for_status()
    except Exception as e:
        print(f"❌ Error fetching the website: {e}")
        return

    # Extract clean text from HTML paragraphs
    soup = BeautifulSoup(response.text, 'html.parser')
    paragraphs = soup.find_all('p')
    web_text = " ".join([p.get_text() for p in paragraphs])[:4000] # Cap text to avoid token limits
    
    if len(web_text) < 100:
        print("❌ Could not extract enough text content from this webpage.")
        return

    # 3. Setup AI Analysis
    print("[2/3] Analyzing data with AI...")
    
    # Expecting the user to store their free API key in environment variables
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("\n⚠️ GEMINI_API_KEY not found in environment variables.")
        api_key = input("Please paste your Gemini API Key to proceed: ").strip()
    
    if not api_key:
        print("❌ Operation cancelled. API Key required.")
        return
        
    genai.configure(api_key=api_key)
    
    # Constructing a clean business analysis prompt
    prompt = f"""
    You are a premium business intelligence analyst. Analyze the following raw text scraped from a business competitor's website. Provide a professional, structured markdown summary highlighting:
    1. Core Value Proposition (What do they sell/solve?)
    2. Key Target Audience
    3. Identified Strengths & Weaknesses based on copy
    4. Marketing or Messaging Angles used

    Raw Web Content:
    \"\"\"{web_text}\"\"\"
    """
    
    # 4. Generate the report
    try:
        model = genai.GenerativeModel("gemini-1.5-flash")
        print("[3/3] Generating final intelligence report...\n")
        response = model.generate_content(prompt)
        
        print("====================================================")
        print("📊 COMPETITOR INTELLIGENCE REPORT (Generated by Bharath-AI-Modules)")
        print("====================================================\n")
        print(response.text)
        print("\n====================================================")
        
    except Exception as e:
        print(f"❌ Error generating AI analysis: {e}")

if __name__ == "__main__":
    scrape_and_analyze()
